### PR TITLE
Minor clean ups

### PR DESCRIPTION
**Pull request by manuel-uberti**
Some various minor fixes:

- comments and docstrings filled
- some minor spelling fixes

Nothing serious, so feel free to discard the PR if you're not interested. :)

### CODE REVIEW

**Comment by laishulu** [comment]
Glad to see your PR.
But the indentation is deliberate.

`define-namespace` is used only for shotening names.
codes inside it are still in the root level.

So please revert the indentation and send PR again.
I will accept the PR then. :-)

**Comment by manuel-uberti** [comment]
Done. :+1:

**Comment by manuel-uberti** [comment]
Did something go wrong with the merging? I can't see my fixes in the latest master.

**Comment by laishulu** [comment]
weird...

How to apply it again?

If not through manual diff?

**Comment by manuel-uberti** [comment]
I opened a new PR to re-apply the lost changes: https://github.com/laishulu/hl-fill-column/pull/2

**Pull request merged**
